[package]
name = "scraper"
version = "0.5.0"

description = "HTML parsing and querying with CSS selectors"
keywords = ["html", "css", "selector", "scraping"]

authors = [
    "Curtis McEnroe <programble@gmail.com>",
    "Vivek Kushwaha <yoursvivek@gmail.com>",
]
license = "ISC"

repository = "https://github.com/programble/scraper"
readme = "README.md"

[dependencies]
cssparser = "0.13"
ego-tree = "0.2.0"
html5ever = "0.21.0"
matches = "0.1.6"
selectors = "0.18.0"
tendril = "0.4.0"
