[package]
name = "scraper"
version = "0.4.0"

description = "HTML parsing and querying with CSS selectors"
keywords = ["html", "css", "selector", "scraping"]

authors = ["Curtis McEnroe <programble@gmail.com>"]
license = "ISC"

documentation = "https://cmcenroe.me/scraper/scraper"
repository = "https://github.com/programble/scraper"
readme = "README.md"

[dependencies]
cssparser = "0.13"
ego-tree = "0.1.0"
html5ever = "0.21.0"
matches = "0.1.6"
selectors = "0.18.0"
tendril = "0.4.0"
